name: hanjanhae
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  http: ^1.2.1

  kakao_flutter_sdk_user: ^1.9.0 # 카카오 로그인 패키지
  google_sign_in: ^6.2.1 # 구글 로그인 패키지
  flutter_naver_login: ^1.8.0 #네이버 로그인 패키지
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/loginicon/googleicon.png
    - assets/loginicon/kakaoicon.png
    - assets/loginicon/navericon.png
    - assets/cocktail.jpeg
    - assets/cocktail1.jpg
    - assets/cocktail2.jpg
    - assets/cocktail3.jpg
  fonts:
    - family: Jalnan
      fonts:
        - asset: assets/fonts/JalnanGothic.otf
        - asset: assets/fonts/JalnanGothicTTF.ttf
