name: hanjanhae
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  http: ^1.2.1 # http 통신 패키지
  sqflite: ^2.0.0+4
  path: ^1.8.0
  kakao_flutter_sdk_user: ^1.9.0 # 카카오 로그인 패키지
  google_sign_in: ^6.2.1 # 구글 로그인 패키지
  flutter_naver_login: ^1.8.0 # 네이버 로그인 패키지
  flutter_bloc: ^8.1.5 # 상태 관리 패키지
  flutter_secure_storage: ^9.0.0 # 데이터 암호화 데이터베이스 패키지
  test: ^1.25.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/alcohol_icon/tequila.png
    - assets/req/cocktail.jpeg
    - assets/req/cocktail1.jpg
    - assets/req/cocktail2.jpg
    - assets/req/cocktail3.jpg

  fonts:
    - family: Jalnan
      fonts:
        - asset: assets/fonts/JalnanGothic.otf
        - asset: assets/fonts/JalnanGothicTTF.ttf
